---
- name: Install Netdata Agent
  #Specify your hosts here
  hosts:
  #Specify your claim token, url, and specfic channel (https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart) 
  vars:
    claim_token: 
    claim_url: 
    channel: 
  become: yes
  #Specify your remote user
  remote_user: 

  tasks:
    #Install WGET as Netdata's kickstart needs it.
    - name: Install wget
      ansible.builtin.package:
          name: wget
          state: present
    #Install Netdata to the default location of your netdata tenant
    - name: Install Netdata Agent via Kickstart
      become: yes
      shell: 
        cmd: |
          wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --claim-token {{ claim_token }} --claim-url {{ claim_url }} --non-interactive {{ channel }}

    #Restart the netdata agent on the server.
    - name: Restart NetData Agent
      ansible.builtin.service:
        name: netdata
        state: restarted
